version: "3.9"

services:
  user-service:
    build: .
    container_name: user-service
    ports:
      - "5001:5001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user-service_db
      - JWT_SECRET=T7bH5KSsPtfAvaTJZpHjZ1NDwGADMxUA
      - JWT_REFRESH_SECRET=fnL5mlAR
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongodb

volumes:
  mongo-data:
