version: "3.8"

services:
  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - baksho-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - baksho-net

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - baksho-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user_service
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/user-service_db
      - JWT_SECRET=T7bH5KSsPtfAvaTJZpHjZ1NDwGADMxUA
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    depends_on:
      mongodb:
        condition: service_started
      service-registry:
        condition: service_healthy
    networks:
      - baksho-net

  campaign-service:
    build: ./campaign-service
    container_name: campaign-service
    ports:
      - "8001:8001"
    environment:
      - EUREKA_SERVER=http://service-registry:8761/eureka
      - APP_HOST=campaign-service
      - APP_PORT=8001
    volumes:
      - ./campaign-service/db_data:/app/db_data
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - baksho-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=sqlite:///./db_data/notifications.db
      - EUREKA_SERVER=http://service-registry:8761/eureka
      - APP_HOST=notification-service
      - APP_PORT=8000
    volumes:
      - notification-db-data:/app/db_data
    depends_on:
      service-registry:
        condition: service_healthy
    networks:
      - baksho-net

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
      - DB_HOST=mysql-db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=payment_db
      - STRIPE_SECRET_KEY=sk_test_51PNCu5RuW4NDldMh2Fhfne9kXcHFULTyfIUOO2hL2MJy6ocbYy1hKqumGoOmM5tG2NvEI9WLPPMy2GugE5PMIo6p00XwNE6Can
      - EUREKA_HOST=service-registry
      - EUREKA_PORT=8761
    depends_on:
      mysql-db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    networks:
      - baksho-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka
      - JWT_SECRET=T7bH5KSsPtfAvaTJZpHjZ1NDwGADMxUA
    depends_on:
      - service-registry
      - user-service
      - campaign-service
      - payment-service
    networks:
      - baksho-net

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=12345678
    depends_on:
      - mongodb
    networks:
      - baksho-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8084:80" # Host port 8084 mapped to container port 80
    environment:
      - PMA_HOST=mysql-db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=12345678
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - baksho-net

volumes:
  mongo-data:
  mysql-data:
  notification-db-data:

networks:
  baksho-net:
    driver: bridge
